#ifndef LIBNESTEDGRID_GLOBAL_H
#define LIBNESTEDGRID_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBNESTEDGRID_LIBRARY)
#  define LIBNESTEDGRIDSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBNESTEDGRIDSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBNESTEDGRID_GLOBAL_H
