#ifndef NESTEDGRID_DEFINITIONS_H
#define NESTEDGRID_DEFINITIONS_H

#include "ogr_core.h"

#define NESTED_GRID_PROJECT_STORAGE_LANDSAT8_METADATA_FILES_FOLDER              "Landsat8_Metadata"
#define NESTED_GRID_PROJECT_STORAGE_SENTINEL2_METADATA_FILES_FOLDER             "Sentinel2_Metadata"

#define NESTED_GRID_PROJECT_TEMPLATES_FOLDER                                            "NestedGridProjectTemplates"
#define NESTED_GRID_PROJECT_LANDSAT8_PATH_ROW_SHAPEFILE_WRS2_DESCENDING_FILE_NAME       "landsat_path_row/wrs2_descending.shp"
#define NESTED_GRID_PROJECT_LANDSAT8_PATH_ROW_SHAPEFILE_WRS2_DESCENDING_CRS_EPSG_CODE   4326
#define NESTED_GRID_PROJECT_LANDSAT8_PATH_ROW_SHAPEFILE_WRS2_DESCENDING_PATH_FIELD      "PATH"
#define NESTED_GRID_PROJECT_LANDSAT8_PATH_ROW_SHAPEFILE_WRS2_DESCENDING_ROW_FIELD       "ROW"

#define NESTED_GRID_PERSISTENCE_FILE_MANAGER_NESTEDGRID_TAG                     "NestedGrid"
#define NESTED_GRID_PERSISTENCE_FILE_MANAGER_CRS_TAG                            "CRS"
#define NESTED_GRID_PERSISTENCE_FILE_MANAGER_CRS_ATTRIBUTE_GEOGRAPHIC_BASE_CRS  "GeographicBaseCrsEpsgCode"
#define NESTED_GRID_PERSISTENCE_FILE_MANAGER_CRS_ATTRIBUTE_PROJ4TEXT            "proj4text"
//#define NESTED_GRID_PERSISTENCE_FILE_MANAGER_CRS_ATTRIBUTE_PROJECTED_CRS        "ProjectedCrs"
#define NESTED_GRID_PERSISTENCE_FILE_MANAGER_CRS_LOCAL_PARAMETERS               "LocalParameters"

#define NESTED_GRID_PERSISTENCE_FILE_MANAGER_SCENES_TAG                         "Scenes"
#define NESTED_GRID_PERSISTENCE_FILE_MANAGER_SCENE_TAG                          "Scene"
#define NESTED_GRID_PERSISTENCE_FILE_MANAGER_SCENE_ATTRIBUTE_ID                 "Id"
#define NESTED_GRID_PERSISTENCE_FILE_MANAGER_SCENE_ATTRIBUTE_TYPE               "Type"
#define NESTED_GRID_PERSISTENCE_FILE_MANAGER_BAND_TAG                           "Band"
#define NESTED_GRID_PERSISTENCE_FILE_MANAGER_BAND_ATTRIBUTE_NUMBER              "Number"
#define NESTED_GRID_PERSISTENCE_FILE_MANAGER_BAND_ATTRIBUTE_TUPLEKEYS           "Tuplekey"
#define NESTED_GRID_PERSISTENCE_FILE_MANAGER_TUPLEKEYS_SEPARATOR                 ";"

#define NESTED_GRID_PERSISTENCE_FILE_MANAGER_ORTHOIMAGES_TAG                         "Orthoimages"
#define NESTED_GRID_PERSISTENCE_FILE_MANAGER_ORTHOIMAGE_TAG                          "Orthoimage"
#define NESTED_GRID_PERSISTENCE_FILE_MANAGER_ORTHOIMAGE_ATTRIBUTE_ID                 "Id"

#define NESTED_GRID_PERSISTENCE_FILE_MANAGER_REMOTESENSINGPRODUCTS_TAG               "RemoteSensingProducts"
#define NESTED_GRID_PERSISTENCE_FILE_MANAGER_REMOTESENSINGPRODUCT_TAG                "RemoteSensingProduct"
#define NESTED_GRID_PERSISTENCE_FILE_MANAGER_REMOTESENSINGPRODUCT_ATTRIBUTE_ID       "Id"
#define NESTED_GRID_PERSISTENCE_FILE_MANAGER_REMOTESENSINGPRODUCT_ATTRIBUTE_TYPE     "Type"
#define NESTED_GRID_PERSISTENCE_FILE_MANAGER_REMOTESENSINGPRODUCT_ATTRIBUTE_COMPUTATION_METHOD     "Computation_Method"
#define NESTED_GRID_PERSISTENCE_FILE_MANAGER_REMOTESENSINGPRODUCT_ATTRIBUTE_DATE     "Date"
#define NESTED_GRID_PERSISTENCE_FILE_MANAGER_REMOTESENSINGPRODUCT_ATTRIBUTE_CONVERSION     "Conversion"
#define NESTED_GRID_PERSISTENCE_FILE_MANAGER_REMOTESENSINGPRODUCT_SEPARATOR_CHARACTER      ":"
#define NESTED_GRID_PERSISTENCE_FILE_MANAGER_REMOTESENSINGPRODUCT_ATTRIBUTE_LOD_TILES   "LodTiles"
#define NESTED_GRID_PERSISTENCE_FILE_MANAGER_REMOTESENSINGPRODUCT_ATTRIBUTE_LOD_GSD   "LodGsd"

#define NESTED_GRID_NO_COMBO_SELECT                                             " ... "

#define NESTED_GRID_DEFINITION_LOD_DEFAULT_VALUE                                 23
#define NESTED_GRID_DEFINITION_LOD_MINVALUE                                      0
#define NESTED_GRID_DEFINITION_LOD_MAXVALUE                                      23
#define NESTED_GRID_COMPUTATION_LATITUDE_DEFAULT_VALUE                           "0.0000"

#define NESTED_GRID_DEFINITION_STORAGE_LOD_DEFAULT_VALUE                        10

#define NESTED_GRID_DEFINITION_GEOMETRIC_RESOLUTION_LOD_DEFAULT_VALUE           12

#define NESTED_GRID_DEFINITION_RADIOMETRIC_RESOLUTION_8                         8
#define NESTED_GRID_DEFINITION_RADIOMETRIC_RESOLUTION_16                        16
#define NESTED_GRID_DEFINITION_RADIOMETRIC_RESOLUTION_32                        32
#define NESTED_GRID_DEFINITION_RADIOMETRIC_RESOLUTION_64                        64
#define NESTED_GRID_DEFINITION_RADIOMETRIC_RESOLUTION_DEFAULT_VALUE             NESTED_GRID_DEFINITION_RADIOMETRIC_RESOLUTION_16


#define NESTED_GRID_DEFINITION_RADIOMETRIC_RESOLUTION_ORIGINAL                  "Original"
#define NESTED_GRID_DEFINITION_RADIOMETRIC_RESOLUTION_8BITS                     "8_bits"

//#define MAINWINDOW_NESTED_GRID_DEFINITION_WORLD_WIDTH_AND_HEIGHT_BASE_DEFAULT_VALUE         256
#define NESTED_GRID_DEFINITION_WORLD_WIDTH_AND_HEIGHT_BASE                       8

#define NESTED_GRID_SHAPEFILE_ROI                                               "ROIs"
#define NESTED_GRID_SHAPEFILE_NUMBER_OF_ROI                                     "ROIs/NumberOfROIs"
#define NESTED_GRID_SHAPEFILE_ROI_TAG                                           "ROIs/ROI_"
#define NESTED_GRID_SHAPEFILE_ROI_STRING_SEPARATOR                              "_"
#define NESTED_GRID_SHAPEFILE_LAST_ROI                                          "ROIs/Last"

#define NESTED_GRID_SHAPEFILE_ROI_TRS_ID_DEFAULT_VALUE                          "ETRS89_SPAIN"
#define NESTED_GRID_SHAPEFILE_ROI_DEFAULT_ID                                    "Europe#1"
#define NESTED_GRID_SHAPEFILE_ROI_CRS_ID_DEFAULT_VALUE                          "4258"
#define NESTED_GRID_SHAPEFILE_ROI_NW_FIRST_COORDINATE_DEFAULT_VALUE             "-25.000000"
#define NESTED_GRID_SHAPEFILE_ROI_NW_SECOND_COORDINATE_DEFAULT_VALUE            "72.000000"
#define NESTED_GRID_SHAPEFILE_ROI_SE_FIRST_COORDINATE_DEFAULT_VALUE             "45.000000"
//#define NESTED_GRID_SHAPEFILE_ROI_SE_SECOND_COORDINATE_DEFAULT_VALUE            "32.0000"
#define NESTED_GRID_SHAPEFILE_ROI_SE_SECOND_COORDINATE_DEFAULT_VALUE            "27.000000"
#define NESTED_GRID_SHAPEFILE_ROI_NW_FIRSTCOOR_TAG                              "NW First Coor:"
#define NESTED_GRID_SHAPEFILE_ROI_NW_SECONDCOOR_TAG                             "NW Second Coor:"
#define NESTED_GRID_SHAPEFILE_ROI_SE_FIRSTCOOR_TAG                              "SE First Coor:"
#define NESTED_GRID_SHAPEFILE_ROI_SE_SECONDCOOR_TAG                             "SE Second Coor:"

#define NESTED_GRID_SHAPEFILE_ROI_NW_LATITUDE_TAG                               "NW Latitude (DEG):"
#define NESTED_GRID_SHAPEFILE_ROI_NW_LONGITUDE_TAG                              "NW Longitude (DEG):"
#define NESTED_GRID_SHAPEFILE_ROI_SE_LATITUDE_TAG                               "SE Latitude (DEG):"
#define NESTED_GRID_SHAPEFILE_ROI_SE_LONGITUDE_TAG                              "SE Longitude (DEG):"
#define NESTED_GRID_SHAPEFILE_ROI_NW_NORTHING_TAG                               "NW Northing (m):"
#define NESTED_GRID_SHAPEFILE_ROI_NW_EASTING_TAG                                "NW Easting (m):"
#define NESTED_GRID_SHAPEFILE_ROI_SE_NORTHING_TAG                               "SE Northing (m):"
#define NESTED_GRID_SHAPEFILE_ROI_SE_EASTING_TAG                                "SE Easting (m):"

#define NESTED_GRID_DEFINITION_TRS_ID_1                                          "WGS84"
#define NESTED_GRID_DEFINITION_TRS_1_CRS_BASE_EPSG_CODE                          4326
#define NESTED_GRID_DEFINITION_TRS_ID_2                                          "ETRS89"
#define NESTED_GRID_DEFINITION_TRS_2_CRS_BASE_EPSG_CODE                          4258
#define NESTED_GRID_DEFINITION_TRS_DEFAULT                                       NESTED_GRID_DEFINITION_TRS_ID_1
#define NESTED_GRID_WGS84_PSEUDO_MERCATOR_EPSG_CODE                              3857

#define NESTED_GRID_DEFINITION_PROJECTION_1                                      "Mercator (2SP)"
#define NESTED_GRID_DEFINITION_PROJECTION_1_PROJ4_CORRESPONDING                  "merc"
#define NESTED_GRID_DEFINITION_PROJECTION_DEFAULT                                NESTED_GRID_DEFINITION_PROJECTION_1

#define NESTED_GRID_DEFINITION_PROJECTION_SCALE_FACTOR_PRECISION                 12

#define NESTED_GRID_DEFINITION_PROJECTION_FALSE_EASTING_DEFAULT_VALUE            0.0
#define NESTED_GRID_DEFINITION_PROJECTION_FALSE_EASTING_MIN_VALUE                0.0
#define NESTED_GRID_DEFINITION_PROJECTION_FALSE_EASTING_MAX_VALUE                10000000.0
#define NESTED_GRID_DEFINITION_PROJECTION_FALSE_EASTING_PRECISION                3

#define NESTED_GRID_DEFINITION_PROJECTION_FALSE_NORTHING_DEFAULT_VALUE           0.0
#define NESTED_GRID_DEFINITION_PROJECTION_FALSE_NORTHING_MIN_VALUE               0.0
#define NESTED_GRID_DEFINITION_PROJECTION_FALSE_NORTHING_MAX_VALUE               10000000.0
#define NESTED_GRID_DEFINITION_PROJECTION_FALSE_NORTHING_PRECISION               3

#define NESTED_GRID_DEFINITION_PROJECTION_STANDARD_PARALLEL_LATITUDE_DEFAULT_VALUE        33.144897290000
#define NESTED_GRID_DEFINITION_PROJECTION_STANDARD_PARALLEL_LATITUDE_MIN_VALUE            0.0
#define NESTED_GRID_DEFINITION_PROJECTION_STANDARD_PARALLEL_LATITUDE_MAX_VALUE            60.0
#define NESTED_GRID_DEFINITION_PROJECTION_STANDARD_PARALLEL_LATITUDE_PRECISION            12

#define NESTED_GRID_DEFINITION_PROJECTION_STANDARD_PARALLEL_BY_LOD_DEFAULT_VALUE  17
#define NESTED_GRID_DEFINITION_PROJECTION_STANDARD_PARALLEL_BY_LOD_MIN_VALUE      15
#define NESTED_GRID_DEFINITION_PROJECTION_STANDARD_PARALLEL_BY_LOD_MAX_VALUE      17

#define NESTED_GRID_DEFINITION_NUMBER_OF_BANDS_DEFAULT_VALUE        7
#define NESTED_GRID_DEFINITION_NUMBER_OF_BANDS_MIN_VALUE            1
#define NESTED_GRID_DEFINITION_NUMBER_OF_BANDS_MAX_VALUE            999

#define NESTED_GRID_DEFINITION_NUMBER_OF_OVERVIEWS_DEFAULT_VALUE        2
#define NESTED_GRID_DEFINITION_NUMBER_OF_OVERVIEWS_MIN_VALUE            0
#define NESTED_GRID_DEFINITION_NUMBER_OF_OVERVIEWS_MAX_VALUE            10

#define NESTED_GRID_EASTING_TAG                                              "Easting (m):"
#define NESTED_GRID_EASTING_DEFAULT_VALUE                                    0.0
#define NESTED_GRID_EASTING_MIN_VALUE                                        -10000000.0
#define NESTED_GRID_EASTING_MAX_VALUE                                        10000000.0
#define NESTED_GRID_EASTING_PRECISION                                        3
#define NESTED_GRID_ROI_EASTING_PRECISION                                    1

#define NESTED_GRID_NORTHING_TAG                                              "Northing (m):"
#define NESTED_GRID_NORTHING_DEFAULT_VALUE                                   0.0
#define NESTED_GRID_NORTHING_MIN_VALUE                                       -10000000.0
#define NESTED_GRID_NORTHING_MAX_VALUE                                       10000000.0
#define NESTED_GRID_NORTHING_PRECISION                                       3
#define NESTED_GRID_ROI_NORTHING_PRECISION                                   1

#define NESTED_GRID_LONGITUDE_TAG                                            "Longitude (DEG):"
#define NESTED_GRID_LONGITUDE_DEFAULT_VALUE                                  0.0
#define NESTED_GRID_LONGITUDE_MIN_VALUE                                      -180.0
#define NESTED_GRID_LONGITUDE_MAX_VALUE                                      180.0
#define NESTED_GRID_LONGITUDE_PRECISION                                      12
#define NESTED_GRID_ROI_LONGITUDE_PRECISION                                  6

#define NESTED_GRID_LATITUDE_TAG                                            "Latitude (DEG):"
#define NESTED_GRID_LATITUDE_DEFAULT_VALUE                                   0.0
#define NESTED_GRID_LATITUDE_MIN_VALUE                                       -90.0
#define NESTED_GRID_LATITUDE_MAX_VALUE                                       90.0
#define NESTED_GRID_LATITUDE_PRECISION                                       12
#define NESTED_GRID_ROI_LATITUDE_PRECISION                                   6

#define NESTED_GRID_PROJ4_LONGLAT_TAG                                            "longlat"

#define NESTED_GRID_DEFINITION_GEOGRAPHIC_COORDINATES_PRECISION                  12
#define NESTED_GRID_DEFINITION_PROJECTED_COORDINATES_PRECISION                   3
#define NESTED_GRID_DEFINITION_SCALE_FACTOR_PRECISION                            8

#define NESTED_GRID_CRS_TAG                                                  "Nested_Grid"

#define NESTED_GRID_DEFINITION_YES                                               "Yes"
#define NESTED_GRID_DEFINITION_NO                                                "No"

#define NESTED_GRID_USE_SMALLER_SPATIAL_RESOLUTION                          "Smaller"
#define NESTED_GRID_USE_HIGHER_SPATIAL_RESOLUTION                           "Higher"

#define NESTED_GRID_RESAMPLING_METHOD_NEAR                                  "near"
#define NESTED_GRID_RESAMPLING_METHOD_BILINEAR                              "bilinear"
#define NESTED_GRID_RESAMPLING_METHOD_CUBIC                                 "cubic"
#define NESTED_GRID_RESAMPLING_METHOD_CUBICSPLINE                           "cubicspline"

#define NESTED_GRID_RASTER_FORMAT_GTIFF                                     "GTiff"
#define NESTED_GRID_RASTER_FORMAT_GTIFF_FILE_EXTENSION                      "tif"

#define NESTED_GRID_COMPRESSION_METHOD_JPEG                                 "JPEG"
#define NESTED_GRID_COMPRESSION_METHOD_LZW                                  "LZW"
#define NESTED_GRID_COMPRESSION_METHOD_NONE                                 "NONE"

#define NESTED_GRID_REMOTESENSINGPRODUCTS_METADATA_TYPE_1                   "file_name"
#define NESTED_GRID_REMOTESENSINGPRODUCTS_METADATA_FILE_NAME_SEPARATOR_CHARACTER_1      "_"

#define NESTED_GRID_SHAPEFILE_FIELD_NAME_LOD                                "lod"
#define NESTED_GRID_SHAPEFILE_FIELD_TYPE_LOD                                OFTInteger
#define NESTED_GRID_SHAPEFILE_FIELD_NAME_TILE_X                             "tile_x"
#define NESTED_GRID_SHAPEFILE_FIELD_TYPE_TILE_X                             OFTInteger
#define NESTED_GRID_SHAPEFILE_FIELD_NAME_TILE_Y                             "tile_y"
#define NESTED_GRID_SHAPEFILE_FIELD_TYPE_TILE_Y                             OFTInteger
#define NESTED_GRID_SHAPEFILE_FIELD_NAME_TUPLEKEY                           "tuplekey"
#define NESTED_GRID_SHAPEFILE_FIELD_TYPE_TUPLEKEY                           OFTString
#define NESTED_GRID_SHAPEFILE_FIELD_NAME_TEST_TUPLEKEY_TO_TILES             "test_tk2ts"
#define NESTED_GRID_SHAPEFILE_FIELD_TYPE_TEST_TUPLEKEY_TO_TILES             OFTInteger
#define NESTED_GRID_SHAPEFILE_FIELD_NAME_TEST_TUPLEKEY_TO_LOD               "test_tk2lo"
#define NESTED_GRID_SHAPEFILE_FIELD_TYPE_TEST_TUPLEKEY_TO_LOD               OFTInteger
#define NESTED_GRID_SHAPEFILE_FIELD_NAME_TEST_CENTER_POINT                  "test_cp"
#define NESTED_GRID_SHAPEFILE_FIELD_TYPE_TEST_CENTER_POINT                  OFTInteger

#define NESTEDGRIDPROJECT_SEPARATOR_CHARACTER                               "#"
#define NESTEDGRIDPROJECT_NESTEDGRID_CRS_DEFINITION_TYPE_EPSGCODE           "EPSG_Code"
#define NESTEDGRIDPROJECT_NESTEDGRID_CRS_DEFINITION_TYPE_PROJ4STRING        "Proj4_String"
#define NESTEDGRIDPROJECT_NUMBEROFPROCESSES_MINVALUE                        1
#define NESTEDGRIDPROJECT_NUMBEROFPROCESSES_MAXVALUE                        10
#define NESTEDGRIDPROJECT_PROCESS_INSERTSCENES                              "Insert_Scenes"
#define NESTEDGRIDPROJECT_PROCESS_INSERTSCENES_NUMBEROFSCENES_MINVALUE      1
#define NESTEDGRIDPROJECT_PROCESS_INSERTSCENES_NUMBEROFSCENES_MAXVALUE      1000

#define NESTEDGRIDPROJECT_NW_ORIGIN_LONGITUDE_TAG                           "INITIAL_NW_ORIGIN_LONGITUDE"
#define NESTEDGRIDPROJECT_NW_ORIGIN_LONGITUDE_MINVALUE                      -180.0
#define NESTEDGRIDPROJECT_NW_ORIGIN_LONGITUDE_MAXVALUE                      180.0

#define NESTEDGRIDPROJECT_NW_ORIGIN_LATITUDE_TAG                            "INITIAL_NW_ORIGIN_LATITUDE"
#define NESTEDGRIDPROJECT_NW_ORIGIN_LATITUDE_MINVALUE                       -90.0
#define NESTEDGRIDPROJECT_NW_ORIGIN_LATITUDE_MAXVALUE                       90.0

#define NESTEDGRIDPROJECT_NW_ROI_PROJECTED_WIDTH_TAG                        "ROI_PROJECTED_WIDTH"
#define NESTEDGRIDPROJECT_ROI_PROJECTED_WIDTH_MINVALUE                      100000.0
#define NESTEDGRIDPROJECT_ROI_PROJECTED_WIDTH_MAXVALUE                      10000000.0

#define NESTEDGRIDPROJECT_GSD_MAXIMUM_LOD_TAG                               "GSD_MAXIMUM_LOD"
#define NESTEDGRIDPROJECT_GSD_MAXIMUM_LOD_MINVALUE                          1.0
#define NESTEDGRIDPROJECT_GSD_MAXIMUM_LOD_MAXVALUE                          1000.0

#define NESTEDGRIDPROJECT_RATIO_IN_TILES_TAG                                "RATIO_IN_TILES"
#define NESTEDGRIDPROJECT_RATIO_IN_TILES_MINVALUE                           2
#define NESTEDGRIDPROJECT_RATIO_IN_TILES_MAXVALUE                           100

#define NESTEDGRIDPROJECT_BASE_TILE_PIXEL_SIZE_TAG                          "BASE_TILE_PIXEL_SIZE_TAG"
#define NESTEDGRIDPROJECT_BASE_TILE_PIXEL_SIZE_MINVALUE                     256
#define NESTEDGRIDPROJECT_BASE_TILE_PIXEL_SIZE_MAXVALUE                     256

#define NESTEDGRIDPROJECT_MAXIMUM_RASTER_FILE_SIZE_TAG                      "MAXIMUM_RASTER_FILE_SIZE"
#define NESTEDGRIDPROJECT_MAXIMUM_RASTER_FILE_SIZE_MINVALUE                 10000.0
#define NESTEDGRIDPROJECT_MAXIMUM_RASTER_FILE_SIZE_MAXVALUE                 1000000.0

#define NESTEDGRIDPROJECT_NESTEDGRID_DEFINITION_FILE_DATETIMEFORMAT         "_yyyyMMdd_hhmmss"
#define NESTEDGRIDPROJECT_NESTEDGRID_DEFINITION_FILE_EXTENSION              ".txt"

#define NESTEDGRIDPROJECT_PROCESS_INSERTORTHOIMAGES                                     "Insert_Orthoimages"
#define NESTEDGRIDPROJECT_PROCESS_INSERTORTHOIMAGES_NUMBEROFORTHOIMAGES_MINVALUE        1
#define NESTEDGRIDPROJECT_PROCESS_INSERTORTHOIMAGES_NUMBEROFORTHOIMAGES_MAXVALUE        1000

#define NESTEDGRIDPROJECT_PROCESS_INSERTREMOTESENSINGPRODUCTS                                       "Insert_RemoteSensingProducts"
#define NESTEDGRIDPROJECT_PROCESS_INSERTREMOTESENSINGPRODUCTS_NUMBEROFORTHOIMAGES_MINVALUE          1
#define NESTEDGRIDPROJECT_PROCESS_INSERTREMOTESENSINGPRODUCTS_NUMBEROFORTHOIMAGES_MAXVALUE          1000

#define NESTEDGRIDPROJECT_NUMBER_OF_BANDS_SEPARATOR_CHARACTER               ":"
#define NESTEDGRIDPROJECT_BANDS_SEPARATOR_CHARACTER                         ","

#define NESTEDGRIDPROJECT_ORTHOIMAGES_GSD_SEPARATOR_CHARACTER               ":"
#define NESTEDGRIDPROJECT_ORTHOIMAGES_GSD_1_VALUE                           0.10
#define NESTEDGRIDPROJECT_ORTHOIMAGES_GSD_1_TAG                             "0.10"
#define NESTEDGRIDPROJECT_ORTHOIMAGES_GSD_1_TOLERANCE                       0.02

#define NESTEDGRIDPROJECT_ORTHOIMAGES_GSD_2_VALUE                           0.25
#define NESTEDGRIDPROJECT_ORTHOIMAGES_GSD_2_TAG                             "0.25"
#define NESTEDGRIDPROJECT_ORTHOIMAGES_GSD_2_TOLERANCE                       0.05

#define NESTEDGRIDPROJECT_ORTHOIMAGES_GSD_3_VALUE                           0.5
#define NESTEDGRIDPROJECT_ORTHOIMAGES_GSD_3_TAG                             "0.50"
#define NESTEDGRIDPROJECT_ORTHOIMAGES_GSD_3_TOLERANCE                       0.10

#define NESTEDGRIDPROJECT_ORTHOIMAGES_GSD_4_VALUE                           30.0
#define NESTEDGRIDPROJECT_ORTHOIMAGES_GSD_4_TAG                             "30.0"
#define NESTEDGRIDPROJECT_ORTHOIMAGES_GSD_4_TOLERANCE                       6.0

#define NESTEDGRIDPROJECT_7ZIP_PATH                                         "7-Zip"
#define NESTEDGRIDPROJECT_7ZIP_COMMAND                                      "7z.exe"

#define NESTEDGRIDPROJECT_TMP_PATH                                          "tmp"

#define NESTEDGRIDPROJECT_VALID_VALUES_FIELDS_SEPARATOR_CHARACTER           ":"
#define NESTEDGRIDPROJECT_VALID_VALUES_DATE_SEPARATOR_CHARACTER             "@"

#define NESTEDGRIDPROJECT_CONVERSION_FROM_DIGITAL_NUMBERS_NULL              "1.0"

#define NESTEDGRIDPROJECT_REMOTESENSINGPRODUCTS_GSD_SEPARATOR_CHARACTER               ":"
#define NESTEDGRIDPROJECT_REMOTESENSINGPRODUCTS_GSD_1_VALUE                           10.0
#define NESTEDGRIDPROJECT_REMOTESENSINGPRODUCTS_GSD_1_TAG                             "10.0"
#define NESTEDGRIDPROJECT_REMOTESENSINGPRODUCTS_GSD_1_TOLERANCE                       2.0

#define NESTEDGRIDPROJECT_REMOTESENSINGPRODUCTS_GSD_2_VALUE                           30.0
#define NESTEDGRIDPROJECT_REMOTESENSINGPRODUCTS_GSD_2_TAG                             "30.0"
#define NESTEDGRIDPROJECT_REMOTESENSINGPRODUCTS_GSD_2_TOLERANCE                       6.0

//#define NESTEDGRIDPROJECT_REMOTESENSINGPRODUCTS_GSD_3_VALUE                           0.5
//#define NESTEDGRIDPROJECT_REMOTESENSINGPRODUCTS_GSD_3_TAG                             "0.50"
//#define NESTEDGRIDPROJECT_REMOTESENSINGPRODUCTS_GSD_3_TOLERANCE                       0.10

//#define NESTEDGRIDPROJECT_REMOTESENSINGPRODUCTS_GSD_4_VALUE                           30.0
//#define NESTEDGRIDPROJECT_REMOTESENSINGPRODUCTS_GSD_4_TAG                             "30.0"
//#define NESTEDGRIDPROJECT_REMOTESENSINGPRODUCTS_GSD_4_TOLERANCE                       6.0

#endif // NESTEDGRID_DEFINITIONS_H
